name: docker_hub_api
description: Docker Hub API for Dart and Flutter
version: 1.0.0
homepage: https://github.com/luizeof/dart-docker-hub-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
