name: docker_hub_api
description: The Docker Registry HTTP API interacts with instances of the docker registry, which is a service to manage information about docker images.
version: 1.0.4
homepage: https://github.com/luizeof/dart-docker-hub-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
